export const SUITES = [
  {
    id: 0,
    campsiteId: 0,
    name: "Best Luxury Accomodations",
    image: "/img/suiteImg/BestLuxuryAccomodation.jpg",
    price: "35.2",
    rating: 5,
    text: "What a magnificent view!",
    author: "Tinus Lorvaldes",
    date: "2018-10-25T16:30Z",
  },
  {
    id: 1,
    campsiteId: 0,
    name: "Independent Owned",
    image: "/img/suiteImg/independentowned.jpg",
    price: "56.2",
    rating: 4,
    text: "The campground was beautiful, but the bugs could bite sometimes.",
    author: "Brennen Ech",
    date: "2017-06-17T03:33Z",
  },
  {
    id: 2,
    campsiteId: 0,
    name: "Executive Suites",
    image: "/img/suiteImg/ExecutiveSuites.jpg",
    price: "70.3",
    rating: 5,
    text: "I caught a world-record-breaking trout here on my last visit.",
    author: "McKenzie Sebastian",
    date: "2019-02-18T18:12Z",
  },
  {
    id: 3,
    campsiteId: 0,
    name: "Mickenny Office Space",
    image: "/img/suiteImg/MickennyOfficeSpace.jpg",
    price: "31.0",
    rating: 5,
    text: "A wonderful place to reconnect with nature.",
    author: "Jordan Runn",
    date: "2019-08-04T20:11Z",
  },
  {
    id: 4,
    campsiteId: 0,
    name: "Coffee Decafe",
    image: "/img/suiteImg/buzyguy.jpg",
    price: "90.7",
    rating: 4,
    text: "The stars at night were a revelation!",
    author: "Ann Dabramov",
    date: "2018-07-23T19:44Z",
  },
  {
    id: 5,
    campsiteId: 1,
    name: "Only 499 Suites",
    image: "/img/suiteImg/only499suites.jpg",
    price: "26.2",
    rating: 4,
    text: "The campground was beautiful, but the bugs could bite sometimes.",
    author: "Brennen Ech",
    date: "2017-06-17T03:33Z",
  },
  {
    id: 6,
    campsiteId: 1,
    name: "Pool Side Suite",
    image: "/img/suiteImg/Poolsidesuite.jpg",
    price: "87.08",
    rating: 5,
    text: "I caught a world-record-breaking trout here on my last visit.",
    author: "McKenzie Sebastian",
    date: "2019-02-18T18:12Z",
  },
  {
    id: 7,
    campsiteId: 1,
    name: "Presidential Suite",
    image: "/img/suiteImg/PresidentialSuite.jpg",
    price: "111.44",
    rating: 5,
    text: "A wonderful place to reconnect with nature.",
    author: "Jordan Runn",
    date: "2019-08-04T20:11Z",
  },
  {
    id: 8,
    campsiteId: 1,
    name: "Private Office Suites",
    image: "/img/suiteImg/PrivateOfficeSuites.jpg",
    price: "100.2",
    rating: 4,
    text: "The stars at night were a revelation!",
    author: "Ann Dabramov",
    date: "2018-07-23T19:44Z",
  },
  {
    id: 9,
    campsiteId: 1,
    name: "Royal carabean Cruises",
    image: "/img/suiteImg/RoyalcarabbeanCruises.jpg",
    price: "30.0",
    rating: 5,
    text: "What a magnificent view!",
    author: "Tinus Lorvaldes",
    date: "2018-10-25T16:30Z",
  },

  {
    id: 12,
    campsiteId: 2,
    name: "Tenerie Spain",
    image: "/img/suiteImg/TenerieSpain.jpg",
    price: "13.24",
    rating: 4,
    text: "The stars at night were a revelation!",
    author: "Ann Dabramov",
    date: "2018-07-23T19:44Z",
  }
];
