export const COFFEES_LOADING = 'COFFEES_LOADING';
export const COFFEES_FAILED = 'COFFEES_FAILED';
export const ADD_COFFEES = 'ADD_COFFEES';

export const SUITES_LOADING = 'SUITES_LOADING';
export const ADD_SUITES = 'ADD_SUITES';
export const SUITES_FAILED = 'SUITES_FAILED';

export const LOCATIONS_LOADING = 'LOCATIONS_LOADING';
export const ADD_LOCATIONS = 'ADD_LOCATIONS';
export const LOCATIONS_FAILED = 'LOCATIONS_FAILED';

export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';