export const COFFEES_LOADING = 'COFFEES_LOADING';
export const COFFEES_FAILED = 'COFFEES_FAILED';
export const ADD_COFFEES = 'ADD_COFFEES';

export const SUITES_LOADING = 'SUITES_LOADING';
export const ADD_SUITES = 'ADD_SUITES';
export const SUITES_FAILED = 'SUITES_FAILED';

export const LOCATIONS_LOADING = 'LOCATIONS_LOADING';
export const ADD_LOCATIONS = 'ADD_LOCATIONS';
export const LOCATIONS_FAILED = 'LOCATIONS_FAILED';

export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';

export const ADD_MESSAGE = 'ADD_MESSAGE';
export const ADD_MESSAGES = 'ADD_MESSAGES';
export const MESSAGES_FAILED = 'MESSAGES_FAILED';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';


export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

